language: python
python:
- '3.5'

sudo: required
dist: trusty

install:
-sudo apt install pandoc context

script: bash tools/travis-deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: dc3e238ed4e4
  - COMMIT_AUTHOR_EMAIL: stefanos1316@gmail.com
