language: python

python:
- '3.5'

sudo: required

dist: trusty

before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-base

install:
- pip install "notebook==4.1" requests jupyter_cms jupyter_dashboards

addons:
  apt_packages:
  - pandoc

script: bash tools/travis-deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: dc3e238ed4e4
  - COMMIT_AUTHOR_EMAIL: stefanos1316@gmail.com
